site_name: Performance Curves
site_url: https://erp12.github.io/performance-curves/
site_description: The ideal way to evaluate binary classifiers.
site_author: Eddie Pantridge

repo_url: https://github.com/erp12/performance-curves
edit_uri: ""

docs_dir: "docs_src"
site_dir: "docs"

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
  - stylesheets/extra.css

nav:
  - Home: README.md
  - API: api.md
  - License: LICENSE.md

# @todo examples.md
# @todo release-notes.md
# @todo CONTRIBUTING.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exclude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_root_heading: yes
            show_object_full_path: no
            show_signature_annotations: no
      watch:
        - docs_src
        - performance_curves
